### ISSUE TITLE
add a tidy = TRUE parameter to enrollment data

### ISSUE THREAD

**Issue by almartin82** [almartin82/njschooldata#22]
so that subgroups can be efficiently pulled out

**Comment by almartin82** [comment]
bump

**Comment by amartinNPS** [comment]
this would really be helpful. @RyanPfleger, the idea here is that instead of only getting many columns of data (each ethnic group, free, reduced, etc) there would be one row per subgroup.  this is is what we do with assessment data.

**Comment by almartin82** [comment]
this would really be helpful. @RyanPfleger, the idea here is that instead of only getting many columns of data (each ethnic group, free, reduced, etc) there would be one row per subgroup. this is is what we do with assessment data.

**Comment by almartin82** [comment]
this would still be a really good idea.

**Comment by cbini** [comment]
:clap:
