### ISSUE TITLE
Missing schools from charter_city

### ISSUE THREAD

**Issue by zmaher** [almartin82/njschooldata#33]
International Academy of Trenton, Trenton STEM-to-Civics, and Great Futures HS for the Health Sciences are missing from charter_city, and Paterson Arts and Science CS has either changed codes or is coded wrong.

**Comment by zmaher** [comment]
(Working on fixing this)

**Comment by zmaher** [comment]
I submitted a fix (https://github.com/almartin82/njschooldata/issues/34) that simply lists Paterson Arts and Science twice. It looks like its code is listed as 6096 everywhere in all enrollment data and in the PARCC data, but the code is listed as 6097 for the 2014 NJ ASK administration.

Perhaps this should be fixed in assess_tidy?

**Comment by almartin82** [comment]
Interesting.  Haven't thought about how to fix apparent data errors in the NJSMART data!

They are usually pretty good about fixing stuff like this.  Maybe call the DOE first and see what they say?

**Comment by zmaher** [comment]
Can do! Do know who the right person to contact would be?

**Comment by almartin82** [comment]
@zmaher do you have any idea when NJ PARCC data is going to get released?  NYSED just released New York scores today...

**Comment by zmaher** [comment]
Don't know when it's going to be public. Schools just got preliminary data, but they're all too early in the process to even announce things for themselves.

**Comment by almartin82** [comment]
@zmaher I am closing this issue as it seems like we have the best fix possible.  hope all is well with you!
