### ISSUE TITLE
error with binding end_year 2018

### ISSUE THREAD

**Issue by RyanPfleger** [almartin82/njschooldata#54]
Here's an example fail:

```
enr_all <- map_df(
  c(2017:2018),
  fetch_enr
)
```

I think the problem is in the `clean_enr_data` function.

Adding the following to `clean_enr_data` inside `enr_types <- list( )` seems to make it work:
    'CDS_Code' = 'character'

That is:

```
clean_enr_data <- function(df) {
  
  enr_types <- list(
    'county_id' = 'character',
    'CDS_Code' = 'character',
    'county_name' = 'character',
    'district_id' = 'character',
    'district_name' = 'character',
    'school_id' = 'character',
    'school_name' = 'character',
    'program_code' = 'character',
    'program_name' = 'character',
    'grade_level' = 'character',
    'white_m' = 'numeric',
    'white_f' = 'numeric',
    'black_m' = 'numeric',
    'black_f' = 'numeric',
    'hispanic_m' = 'numeric',
    'hispanic_f' = 'numeric',
    'asian_m' = 'numeric',
    'asian_f' = 'numeric',
    'native_american_m' = 'numeric',
    'native_american_f' = 'numeric',
    'pacific_islander_m' = 'numeric',
    'pacific_islander_f' = 'numeric',
    'multiracial_m' = 'numeric',
    'multiracial_f' = 'numeric',
    'free_lunch' = 'numeric',
    'reduced_lunch' = 'numeric',
    'lep' = 'numeric',
    'migrant' = 'numeric',
    'row_total' = 'numeric',
    'homeless' = 'numeric',
    'special_ed' = 'numeric',
    'title_1' = 'numeric',
    'end_year' = 'numeric'
  )
  
  df <- as.data.frame(df)
  
  #some old files (eg 02-03) have random, unlabeled rows.  kill those.
  df <- df[nchar(df$county_name) >0, ]
  
  for (i in 1:ncol(df)) {
    z = enr_types[[names(df)[i]]]
    if (z=='numeric') {
      df[, i] <- as.numeric(df[, i])
    } else if (z=='character') {
      df[, i] <- trim_whitespace(as.character(df[, i]))
      
    }
  }
  
  #make CDS_code
  df$CDS_Code <- paste0(
    stringr::str_pad(df$county_id, width=2, side='left', pad='0'),
    stringr::str_pad(df$district_id, width=4, side='left', pad='0'),
    stringr::str_pad(df$school_id, width=3, side='left', pad='0')
  )
  
  return(df)  
}

```

**Comment by RyanPfleger** [comment]
Also, program_name doesn't seem to fill correctly. E.g., "Total" is missing (I presume it can be derived from program_code == 55)

**Comment by RyanPfleger** [comment]
And free_lunch and reduced_lunch data don't appear.

**Comment by almartin82** [comment]
Hey Ryan,

Three issues here! 

- [ ]  CDS_Code in `clean_enr_data`

- [ ]  program_names

- [ ] missing free and reduced lunch

**Comment by almartin82** [comment]
Program names is 100% on point - because these changed year over year, I've maintained a file that has the program codes and conversions.  See [this] commit to see what needs to be changed YOY - 

- add the new data to `program_codes_clean.csv`
- run the `prog` block in `sysdata.Rmd`
- that saves / updates `program_codes.Rda` which gets loaded into the package namespace on load

**Comment by almartin82** [comment]
the issue with `clean_enr_data` is I think a phantom - it is true that the function won't work if the input data has the `CDS_Code` field.  If you check the raw data (`ex <- get_raw_enr(2018)`) you'll see that the `CDS_Code` isn't in the original data, it's something that gets made by `njschooldata`.  I wasn't able to reproduce this issue - I wrote some tests and I think it is OK now.
