### ISSUE TITLE
Free / reduced lunch data not available in NJDoE data source

### ISSUE THREAD

**Issue by RyanPfleger** [almartin82/njschooldata#55]
The NJDoE variable list for 2017-18 [here ](http://www.nj.gov/education/data/enr/enr18/stat_doc.htm) doesn't include FRL. 

However, the prior year [here](http://www.nj.gov/education/data/enr/enr17/stat_doc.htm), does include it.

How can we get NJDoE to include data they have made available for ~20 years?

**Comment by almartin82** [comment]
Confirming that I don't see these variables in the 2017-18 data.

fields that are missing:
```
[1] "free_lunch"    "reduced_lunch" "lep"          
[4] "migrant"    
```

**Comment by almartin82** [comment]
Request has been made to the DOE, I'll update if we hear more.

**Comment by almartin82** [comment]
Not sure when these appeared in the 2018 file, but I am seeing this data now
